apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  labels:
    app: litellm
spec:
  replicas: 2  # 고가용성을 위해 2개로 증가
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - litellm
            topologyKey: kubernetes.io/hostname
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-stable
        ports:
        - containerPort: 4000
        env:
          - name: AZURE_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: azure-api-key
          - name: AZURE_API_BASE
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: azure-api-base
          - name: AZURE_API_VERSION
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: azure-api-version
          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: gemini-api-key
          - name: LITELLM_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: litellm-master-key
          - name: LITELLM_SALT_KEY
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: litellm-salt-key
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: database-url
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: litellm-config