apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui-v2
  namespace: default
  labels:
    app: openwebui-v2
    ab-test-group: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui-v2
  template:
    metadata:
      labels:
        app: openwebui-v2
        ab-test-group: openwebui
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - openwebui-v2
              topologyKey: kubernetes.io/hostname
      containers:
        - name: openwebui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_BASE_URL
              value: http://litellm:4000/
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: litellm-master-key
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: openwebui-data
              mountPath: /app/backend/data
      volumes:
        - name: openwebui-data
          persistentVolumeClaim:
            claimName: openwebui-v2-data-pvc