apiVersion: v1
kind: Service
metadata:
  name: openwebui-v1-metrics
  namespace: default
  labels:
    app: openwebui-v1
    metrics: "true"
spec:
  selector:
    app: openwebui-v1
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: litellm-metrics
  namespace: default
  labels:
    app: litellm
    metrics: "true"
spec:
  selector:
    app: litellm
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090